### ISSUE TITLE
[Question] Usage of 'vm' variable unclear - vueify compatiblilty

### ISSUE THREAD

**Issue by thorsteneckel** [kikyous/sprockets-vue#1]
Hi there!

First: reeeeally nice gem! I saw your commit adding the usage of a "vm" variable here: https://github.com/kikyous/sprockets-vue/commit/cc4ad7fbb797275d28ae2a0c2a18d3de6d102f05

You wrote that this is done because of bugs. What were the bugs? I ask because I would like to avoid this variable and use the export default variant like described in the vueify README:

Vanilla JS:
https://github.com/vuejs/vueify/blame/master/README.md#L22

Coffee:
https://github.com/vuejs/vueify/blame/master/README.md#L46

This will provide a switch from or to vueify which would be much appreciated.

//EDIT:
In some of the forks something similar is done: https://github.com/msnider/sprockets-vue/commit/0613a630b2ba068592254d621af12a2e1b7e75a3

**Comment by kikyous** [comment]
compiled javascript has expression at first line in some case:

```coffeescript
{
  computed:
    isAdmin: ->
      'admin' in this.roles
} 
```

```javascript
var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

({
  computed: {
    isAdmin: function() {
      return indexOf.call(this.roles, 'admin') >= 0;
    }
  }
});
```
assign the output to a var will cause a error.
this is the bug😬

**Comment by kikyous** [comment]
use the export default variant is a good idea👏

I will look into it❤️

**Comment by kikyous** [comment]
in 0.1.0 you can use vueify style `module.exports`👏
