### ISSUE TITLE
uninitialized constant Babel

### ISSUE THREAD

**Issue by stevenayers** [kikyous/sprockets-vue#2]
When I try to browse to the application I get the following error:

`uninitialized constant Babel`

Stacktrace:

`sprockets-vue (0.0.6) lib/sprockets/vue/script.rb:15:in 'block in singleton class'
sprockets-vue (0.0.6) lib/sprockets/vue/script.rb:27:in 'block in call'
sprockets (3.7.0) lib/sprockets/cache.rb:85:in 'fetch'
sprockets-vue (0.0.6) lib/sprockets/vue/script.rb:21:in 'call'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in 'call_processor'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in 'block in call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'reverse_each'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in 'call_processor'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in 'block in call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'reverse_each'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'call_processors'
sprockets (3.7.0) lib/sprockets/loader.rb:134:in 'load_from_unloaded'
sprockets (3.7.0) lib/sprockets/loader.rb:60:in 'block in load'
sprockets (3.7.0) lib/sprockets/loader.rb:317:in 'fetch_asset_from_dependency_cache'
sprockets (3.7.0) lib/sprockets/loader.rb:44:in 'load'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in 'block in initialize'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in 'load'
sprockets (3.7.0) lib/sprockets/bundle.rb:23:in 'block in call'
sprockets (3.7.0) lib/sprockets/utils.rb:196:in 'dfs'
sprockets (3.7.0) lib/sprockets/bundle.rb:24:in 'call'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in 'call_processor'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in 'block in call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'reverse_each'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in 'call_processors'
sprockets (3.7.0) lib/sprockets/loader.rb:134:in 'load_from_unloaded'
sprockets (3.7.0) lib/sprockets/loader.rb:60:in 'block in load'
sprockets (3.7.0) lib/sprockets/loader.rb:317:in 'fetch_asset_from_dependency_cache'
sprockets (3.7.0) lib/sprockets/loader.rb:44:in 'load'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in 'block in initialize'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in 'load'
sprockets (3.7.0) lib/sprockets/base.rb:66:in 'find_asset'
sprockets (3.7.0) lib/sprockets/base.rb:73:in 'find_all_linked_assets'
sprockets (3.7.0) lib/sprockets/manifest.rb:142:in 'block in find'
sprockets (3.7.0) lib/sprockets/legacy.rb:114:in 'block (2 levels) in logical_paths'
sprockets (3.7.0) lib/sprockets/path_utils.rb:228:in 'block in stat_tree'
sprockets (3.7.0) lib/sprockets/path_utils.rb:212:in 'block in stat_directory'
sprockets (3.7.0) lib/sprockets/path_utils.rb:209:in 'each'
sprockets (3.7.0) lib/sprockets/path_utils.rb:209:in 'stat_directory'
sprockets (3.7.0) lib/sprockets/path_utils.rb:227:in 'stat_tree'
sprockets (3.7.0) lib/sprockets/legacy.rb:105:in 'each'
sprockets (3.7.0) lib/sprockets/legacy.rb:105:in 'block in logical_paths'
sprockets (3.7.0) lib/sprockets/legacy.rb:104:in 'each'
sprockets (3.7.0) lib/sprockets/legacy.rb:104:in 'logical_paths'
sprockets (3.7.0) lib/sprockets/manifest.rb:140:in 'find'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in 'each'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in 'map'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in 'precompiled_assets'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:35:in 'asset_precompiled?'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:251:in 'block (3 levels) in <class:Railtie>'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in 'precompiled?'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:363:in 'raise_unless_precompiled_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:348:in 'find_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in 'block in lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in 'block in resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in 'each'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in 'detect'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in 'resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in 'lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:170:in 'block in stylesheet_link_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in 'map'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in 'stylesheet_link_tag'
app/views/layouts/application.html.erb:7:in '_app_views_layouts_application_html_erb__3926669798929650012_70339015382500'
actionview (5.0.1.rc2) lib/action_view/template.rb:159:in 'block in render'
activesupport (5.0.1.rc2) lib/active_support/notifications.rb:166:in 'instrument'
actionview (5.0.1.rc2) lib/action_view/template.rb:354:in 'instrument'
actionview (5.0.1.rc2) lib/action_view/template.rb:157:in 'render'
actionview (5.0.1.rc2) lib/action_view/renderer/template_renderer.rb:66:in 'render_with_layout'
actionview (5.0.1.rc2) lib/action_view/renderer/template_renderer.rb:52:in 'render_template'
actionview (5.0.1.rc2) lib/action_view/renderer/template_renderer.rb:14:in 'render'
actionview (5.0.1.rc2) lib/action_view/renderer/renderer.rb:42:in 'render_template'
actionview (5.0.1.rc2) lib/action_view/renderer/renderer.rb:23:in 'render'
actionview (5.0.1.rc2) lib/action_view/rendering.rb:103:in '_render_template'
actionpack (5.0.1.rc2) lib/action_controller/metal/streaming.rb:217:in '_render_template'
actionview (5.0.1.rc2) lib/action_view/rendering.rb:83:in 'render_to_body'
actionpack (5.0.1.rc2) lib/action_controller/metal/rendering.rb:52:in 'render_to_body'
actionpack (5.0.1.rc2) lib/action_controller/metal/renderers.rb:142:in 'render_to_body'
actionpack (5.0.1.rc2) lib/abstract_controller/rendering.rb:26:in 'render'
actionpack (5.0.1.rc2) lib/action_controller/metal/rendering.rb:36:in 'render'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:44:in 'block (2 levels) in render'
activesupport (5.0.1.rc2) lib/active_support/core_ext/benchmark.rb:12:in 'block in ms'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in 'realtime'
activesupport (5.0.1.rc2) lib/active_support/core_ext/benchmark.rb:12:in 'ms'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:44:in 'block in render'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:87:in 'cleanup_view_runtime'
activerecord (5.0.1.rc2) lib/active_record/railties/controller_runtime.rb:25:in 'cleanup_view_runtime'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:43:in 'render'
actionpack (5.0.1.rc2) lib/action_controller/metal/implicit_render.rb:36:in 'default_render'
actionpack (5.0.1.rc2) lib/action_controller/metal/basic_implicit_render.rb:4:in 'send_action'
actionpack (5.0.1.rc2) lib/abstract_controller/base.rb:188:in 'process_action'
actionpack (5.0.1.rc2) lib/action_controller/metal/rendering.rb:30:in 'process_action'
actionpack (5.0.1.rc2) lib/abstract_controller/callbacks.rb:20:in 'block in process_action'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:126:in 'call'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:506:in 'block (2 levels) in compile'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:455:in 'call'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:101:in '__run_callbacks__'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:750:in '_run_process_action_callbacks'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:90:in 'run_callbacks'
actionpack (5.0.1.rc2) lib/abstract_controller/callbacks.rb:19:in 'process_action'
actionpack (5.0.1.rc2) lib/action_controller/metal/rescue.rb:20:in 'process_action'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:32:in 'block in process_action'
activesupport (5.0.1.rc2) lib/active_support/notifications.rb:164:in 'block in instrument'
activesupport (5.0.1.rc2) lib/active_support/notifications/instrumenter.rb:21:in 'instrument'
activesupport (5.0.1.rc2) lib/active_support/notifications.rb:164:in 'instrument'
actionpack (5.0.1.rc2) lib/action_controller/metal/instrumentation.rb:30:in 'process_action'
actionpack (5.0.1.rc2) lib/action_controller/metal/params_wrapper.rb:248:in 'process_action'
activerecord (5.0.1.rc2) lib/active_record/railties/controller_runtime.rb:18:in 'process_action'
actionpack (5.0.1.rc2) lib/abstract_controller/base.rb:126:in 'process'
actionview (5.0.1.rc2) lib/action_view/rendering.rb:30:in 'process'
actionpack (5.0.1.rc2) lib/action_controller/metal.rb:190:in 'dispatch'
actionpack (5.0.1.rc2) lib/action_controller/metal.rb:262:in 'dispatch'
actionpack (5.0.1.rc2) lib/action_dispatch/routing/route_set.rb:50:in 'dispatch'
actionpack (5.0.1.rc2) lib/action_dispatch/routing/route_set.rb:32:in 'serve'
actionpack (5.0.1.rc2) lib/action_dispatch/journey/router.rb:39:in 'block in serve'
actionpack (5.0.1.rc2) lib/action_dispatch/journey/router.rb:26:in 'each'
actionpack (5.0.1.rc2) lib/action_dispatch/journey/router.rb:26:in 'serve'
actionpack (5.0.1.rc2) lib/action_dispatch/routing/route_set.rb:725:in 'call'
rack (2.0.1) lib/rack/etag.rb:25:in 'call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in 'call'
rack (2.0.1) lib/rack/head.rb:12:in 'call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in 'context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/cookies.rb:613:in 'call'
activerecord (5.0.1.rc2) lib/active_record/migration.rb:553:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/callbacks.rb:38:in 'block in call'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:97:in '__run_callbacks__'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:750:in '_run_call_callbacks'
activesupport (5.0.1.rc2) lib/active_support/callbacks.rb:90:in 'run_callbacks'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/callbacks.rb:36:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/executor.rb:12:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/remote_ip.rb:79:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in 'call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in 'call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in 'block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in 'catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/show_exceptions.rb:31:in 'call'
railties (5.0.1.rc2) lib/rails/rack/logger.rb:36:in 'call_app'
railties (5.0.1.rc2) lib/rails/rack/logger.rb:24:in 'block in call'
activesupport (5.0.1.rc2) lib/active_support/tagged_logging.rb:69:in 'block in tagged'
activesupport (5.0.1.rc2) lib/active_support/tagged_logging.rb:26:in 'tagged'
activesupport (5.0.1.rc2) lib/active_support/tagged_logging.rb:69:in 'tagged'
railties (5.0.1.rc2) lib/rails/rack/logger.rb:24:in 'call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/request_id.rb:24:in 'call'
rack (2.0.1) lib/rack/method_override.rb:22:in 'call'
rack (2.0.1) lib/rack/runtime.rb:22:in 'call'
activesupport (5.0.1.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/executor.rb:12:in 'call'
actionpack (5.0.1.rc2) lib/action_dispatch/middleware/static.rb:136:in 'call'
rack (2.0.1) lib/rack/sendfile.rb:111:in 'call'
railties (5.0.1.rc2) lib/rails/engine.rb:522:in 'call'
puma (3.6.2) lib/puma/configuration.rb:225:in 'call'
puma (3.6.2) lib/puma/server.rb:578:in 'handle_request'
puma (3.6.2) lib/puma/server.rb:415:in 'process_client'
puma (3.6.2) lib/puma/server.rb:275:in 'block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in 'block in spawn_thread'
`

**Comment by kikyous** [comment]
do you use `<script lang='es6'>` ?
It is not supported now.

**Comment by stevenayers** [comment]
Yes, that's the problem then. Do you have any plans to support es6 in the future?

**Comment by kikyous** [comment]
Yes @Stevea37

**Comment by stevenayers** [comment]
@kikyous Thanks, If I have time I'll try to contribute that update.
