### ISSUE TITLE
Using ERB?

### ISSUE THREAD

**Issue by turizoft** [kikyous/sprockets-vue#6]
Is it possible to use erb inside the vue file? For example for loading image assets.

**Comment by kikyous** [comment]
yes , you can rename .vue file to .vue.erb
for example:

test.vue.erb
```html
<template>
  <div>
    <%= image_tag '3.jpg' %>
  </div>
</template>
```

**Comment by turizoft** [comment]
Awesome!

**Comment by Chaitanya40** [comment]
I tried renaming my .vue to vue.erb, but I it says that my component is not registered. Need help regarding this
